### ISSUE TITLE
Add a property to register classes

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-fury#9]
Sometimes users don't want to include an extra annotation to their classes, or the classes are thridparty classes, users can't change it. Or users want make it configurable. We may need to allow such usage:
```yaml
quarkus.
  fury:
    registered:
      - demo.Foo: 300
      - demo.Bar: 301
    serializable:
      - demo.A
      - demo.B
```
